### ISSUE TITLE
嗨，校友，一点小建议。

### ISSUE THREAD

**Issue by nature2608** [BoringCat/minieap-openwrt#1]
`/etc/minieap.conf.gpk: ISO-8859 text` 
gpk是否书写错误？
另外东校区的服务名为：学生DHCP用户
白云校区为：学生Web包月计费
[中文服务名问题可以看这个issus](https://github.com/updateing/minieap/issues/51#issuecomment-544347764)
客户端使用的DHCP方式是：认证后
[DHCP二次认证问题](https://github.com/updateing/minieap/issues/53)
最后，原来mentohust也是可以用的（v2校验的，模拟win客户端），需要带上正确服务名的mpf即可。欢迎多交流

**Comment by BoringCat** [comment]
> `/etc/minieap.conf.gpk: ISO-8859 text`
> gpk是否书写错误？

这条是 `file /etc/minieap.conf.gpk` 的输出，文件是用 `iconv -t gbk /etc/minieap.conf > /etc/minieap.conf.gpk` 转编码出来的

> 另外东校区的服务名为：学生DHCP用户
> 白云校区为：学生Web包月计费
> [中文服务名问题可以看这个issus](https://github.com/updateing/minieap/issues/51#issuecomment-544347764)

我是本部这边的二五仔网管：），白云那边的情况不太清楚😢

> 客户端使用的DHCP方式是：认证后
> [DHCP二次认证问题](https://github.com/updateing/minieap/issues/53)

我这边测试的结果是：如果不使用二次认证，服务器会提示你不是动态获取IP，不给用。使用二次认证就能过。    

> 最后，原来mentohust也是可以用的（v2校验的，模拟win客户端），需要带上正确服务名的mpf即可。欢迎多交流

mentohust不知道为什么我路由器上面的版本无法通过校验，明明版本号是6.84，它永远只能识别到5.0🤬。所以才有了这个项目。  

-------------------------
讲真，兄弟你是哪个校区的，有没有兴趣加入网管：）（二五仔组组长，在线拉人）

**Comment by nature2608** [comment]
我们学校放的比较宽，没有开客户端防破解校验。
dhcp方式不能使用认证前及认证后是minieap的bug，在发送包的时候没有带上mac，ip，mask等信息。

> mentohust不知道为什么我路由器上面的版本无法通过校验，明明版本号是6.84，它永远只能识别到5.0🤬。所以才有了这个项目。
这个是缺少一点必要的认证字段，使用mpf补上去就行。

我已经大四啦，要毕业了，只是比较喜欢研究这个。
[此项目也能适用我们学校](https://github.com/shanzhaozhen/mentohust_for_zqu)，minieap和此mentohust都是模拟linux客户端。
我也修改了minieap，mentohust（模拟linux客户端），jmpsupplicant（此项目服务名直接发送gbk编码的16进制，不需要使用iconv转换）。还是直接在原mentohust上加mpf来的直接，不需要改代码。
我其实很期待在我们学校当网管的哈哈，不过我是插本上来的所以时间不够，所以。。。。😀
